In [6]:
import numpy as np

In [7]:
def gauss_seidel(A, b, tol=1e-3, max_iter=100):
    n = len(A)
    x = np.zeros(n)  # Inicializa la solución con ceros

    print("\nIteraciones del método de Gauss-Seidel:")
    for k in range(max_iter):
        x_old = np.copy(x)  # Guarda la iteración anterior

        for i in range(n):
            sum_ax = sum(A[i, j] * x[j] for j in range(n) if i != j)
            x[i] = (b[i] - sum_ax) / A[i, i]

        diff = np.linalg.norm(x - x_old)  # Diferencia entre iteraciones
        print(f"Iteración {k+1}: x = {x}")

        if diff < tol:  # Verifica si ha convergido
            print("\n¡Convergencia alcanzada!\n")
            return x, k + 1

    return None  # No converge

In [9]:
# Ejercicio 4 Sistema de ecuaciones a
A = np.array([[3, -1, 1],
              [3, 6, 2],
              [3, 3, 7]])
b = np.array([1, 0, 4])

# Resuelve el sistema utilizando Gauss-Seidel
solution = gauss_seidel(A, b)

# Mostrar el resultado final
if solution:
    x, iterations = solution
    print("Solución:")
    print(x)
    print("Número de iteraciones:", iterations)
else:
    print("El método de Gauss-Seidel no convergió dentro del número máximo de iteraciones.")


Iteraciones del método de Gauss-Seidel:
Iteración 1: x = [ 0.33333333 -0.16666667  0.5       ]
Iteración 2: x = [ 0.11111111 -0.22222222  0.61904762]
Iteración 3: x = [ 0.05291005 -0.23280423  0.64852608]
Iteración 4: x = [ 0.03955656 -0.23595364  0.65559875]
Iteración 5: x = [ 0.0361492  -0.23660752  0.65733928]
Iteración 6: x = [ 0.03535107 -0.23678863  0.65775895]

¡Convergencia alcanzada!

Solución:
[ 0.03535107 -0.23678863  0.65775895]
Número de iteraciones: 6


In [10]:
# Ejercicio 4 Sistema de ecuaciones b
A = np.array([[10, -1, 0],
              [-1, 10, -2],
              [0, -2, 10]])
b = np.array([9, 7, 6])

solution = gauss_seidel(A, b)
# Mostrar el resultado final
if solution:
    x, iterations = solution
    print("Solución:")
    print(x)
    print("Número de iteraciones:", iterations)
else:
    print("El método de Gauss-Seidel no convergió dentro del número máximo de iteraciones.")


Iteraciones del método de Gauss-Seidel:
Iteración 1: x = [0.9   0.79  0.758]
Iteración 2: x = [0.979  0.9495 0.7899]
Iteración 3: x = [0.99495  0.957475 0.791495]
Iteración 4: x = [0.9957475  0.95787375 0.79157475]

¡Convergencia alcanzada!

Solución:
[0.9957475  0.95787375 0.79157475]
Número de iteraciones: 4


In [11]:
# Ejercicio 4 Sistema de ecuaciones c
A = np.array([[10, 5, 0, 0],
              [5, 10, -4, 0],
              [0, -4, 8, -1],
              [0, 0, -1, 5]])
b = np.array([6, 25, -11, -11])

solution = gauss_seidel(A, b)
# Mostrar el resultado final
if solution:
    x, iterations = solution
    print("Solución:")
    print(x)
    print("Número de iteraciones:", iterations)
else:
    print("El método de Gauss-Seidel no convergió dentro del número máximo de iteraciones.")


Iteraciones del método de Gauss-Seidel:
Iteración 1: x = [ 0.6    2.2   -0.275 -2.255]
Iteración 2: x = [-0.5       2.64     -0.336875 -2.267375]
Iteración 3: x = [-0.72        2.72525    -0.29579687 -2.25915938]
Iteración 4: x = [-0.762625    2.76299375 -0.27589805 -2.25517961]
Iteración 5: x = [-0.78149687  2.78038922 -0.26670284 -2.25334057]
Iteración 6: x = [-0.79019461  2.78841617 -0.26245949 -2.2524919 ]
Iteración 7: x = [-0.79420808  2.79212025 -0.26050136 -2.25210027]
Iteración 8: x = [-0.79606012  2.79382952 -0.25959778 -2.25191956]
Iteración 9: x = [-0.79691476  2.79461827 -0.25918081 -2.25183616]
Iteración 10: x = [-0.79730913  2.79498224 -0.2589884  -2.25179768]

¡Convergencia alcanzada!

Solución:
[-0.79730913  2.79498224 -0.2589884  -2.25179768]
Número de iteraciones: 10


In [14]:
# Ejercicio 4 Sistema de ecuaciones c
A = np.array([[4, 1, 1, 0, 1],
              [-1, -3, 1, 1, 0],
              [2, 1, 5, -1, -1],
              [-1, -1, -1, 4, 0],
              [0, 2, -1, 1, 4]])
b = np.array([6, 6, 6, 6, 6])

solution = gauss_seidel(A, b)
# Mostrar el resultado final
if solution:
    x, iterations = solution
    print("Solución:")
    print(x)
    print("Número de iteraciones:", iterations)
else:
    print("El método de Gauss-Seidel no convergió dentro del número máximo de iteraciones.")


Iteraciones del método de Gauss-Seidel:
Iteración 1: x = [ 1.5     -2.5      1.1      1.525    2.64375]
Iteración 2: x = [ 1.1890625  -1.52135417  1.86239583  1.88252604  2.25564453]
Iteración 3: x = [ 0.85082845 -1.03530219  1.89436317  1.92747236  2.0093738 ]
Iteración 4: x = [ 0.7828913  -0.98701859  1.87161643  1.91687229  1.98219533]
Iteración 5: x = [ 0.78330171 -0.998271    1.86614704  1.91279444  1.98747365]
Iteración 6: x = [ 0.78616258 -1.00240703  1.86606999  1.91245638  1.98960692]
Iteración 7: x = [ 0.78668253 -1.00271872  1.86628339  1.9125618   1.98978976]

¡Convergencia alcanzada!

Solución:
[ 0.78668253 -1.00271872  1.86628339  1.9125618   1.98978976]
Número de iteraciones: 7
